#!/bin/bash
#------------------------------------------------------------------------------#
# Find all variables in script directory
find_var_fn() {
  find . -type f -name "*.sh" \
    ! -path "./.git/*" \
    ! -name "incl.sh" \
    | xargs grep -o -e "{[^}]*}" | sort | uniq
}
#------------------------------------------------------------------------------#
# Set Script base directory
	#base_dir() {
	#	_install_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	#}
#------------------------------------------------------------------------------#
# Execute to populate configs
source_conf_scripts() {
  find . -type f -name "*.conf" \
    ! -path "./.git/*" \
    | sed 's/\.\///g' \
    | awk '{print"source "$0}' > incl.sh
}
#------------------------------------------------------------------------------#
# Execute to set mode on scripts
source_set_mod() {
  find . -type f -name "*.sh" \
    ! -path "./.git/*" \
    ! -name "incl.sh" \
    | xargs chmod 644
}
#------------------------------------------------------------------------------#
# Execute to populate source scripts
source_sh_scripts() {
    find . -type f -name "*.sh" \
      ! -path "./.git/*" \
      ! -name "incl.sh" \
      | sed 's/\.\///g' \
      | awk '{print"source "$0}' >> incl.sh
}
#------------------------------------------------------------------------------#
# Create Source File
  source_conf_scripts
  source_sh_scripts
  source_set_mod
#------------------------------------------------------------------------------#
# Set Sources
  source incl.sh
#------------------------------------------------------------------------------#
# HomeBridge Menu
homebridge_menu()  {
	## Header
		HEADING="Homebridge Menu"
	## Write out the menu options array
		### Use Double Quotes for Text
			l0=(
				"Install systemd Homebridge service files"
        "Homebridge Configuration Install"
				"Return"
			)
	## Map Menu to command Array
		### Use Single Quotes for Commands
			opt0=(
				'_hb_install_main'
        '_hb_config_install'
				'main_menu'
				)
	## Execute Menu Function
		_g_menu_fn
}
#------------------------------------------------------------------------------#
# Pool Menu
pool_menu()  {
	## Header
		HEADING="Pool Controller"
	## Write out the menu options array
		### Use Double Quotes for Text
			l0=(
				"Nodejs-poolController install"
				"nodejs-poolController service setup"
				"Return"
			)
	## Map Menu to command Array
		### Use Single Quotes for Commands
			opt0=(
				'_pool_controller_install'
				'_pool_controller_service_install'
				'main_menu'
				)
	## Execute Menu Function
		_g_menu_fn
}
#------------------------------------------------------------------------------#
# systemd service management menu
systemd_menu()  {
	## Header
		HEADING="systemd service management"
	## Write out the menu options array
		### Use Double Quotes for Text
			l0=(
				"service status"
        "restart service"
        "enable service"
        "disable service"
        "start service"
        "stop service"
        "daemon reload"
				"Return"
			)
	## Map Menu to command Array
		### Use Single Quotes for Commands
			opt0=(
				'_sysd_service_status'
        '_sysd_service_restart'
        '_sysd_service_enable'
        '_sysd_service_disable'
        '_sysd_service_start'
        '_sysd_service_stop'
        '_sysd_reload_daemon'
				'main_menu'
				)
	## Execute Menu Function
		_g_menu_fn
}
#------------------------------------------------------------------------------#
# System Menu
system_menu()  {
	## Header
		HEADING="System Menu"
	## Write out the menu options array
		### Use Double Quotes for Text
			l0=(
				"Update Raspbian Base System"
				"Install Dependencies"
				"NodeJS install"
				"Return"
			)
	## Map Menu to command Array
		### Use Single Quotes for Commands
			opt0=(
				'_system_update'
				'_system_depends_install'
				'_nodejs_install'
				'main_menu'
				)
	## Execute Menu Function
		_g_menu_fn
}
#------------------------------------------------------------------------------#
# Main Menu
main_menu()  {
	## Header
		HEADING="HomePi"
	## Write out the menu options array
		### Use Double Quotes for Text
			l0=(
				"System Menu"
				"Homebridge Menu"
				"npm extra installations"
				"Pool PI Menu"
				"systemd Service Management"
				"Exit"
			)
	## Map Menu to command Array
		### Use Single Quotes for Commands
			opt0=(
				'system_menu'
				'homebridge_menu'
				'_node_extras_setup'
				'pool_menu'
				'systemd_menu'
				'exit'
				)
	## Execute Menu Function
		_g_menu_fn
}
#------------------------------------------------------------------------------#
# Execute set color function
 _set_colors
#------------------------------------------------------------------------------#
# Execute super user test
 _su_test
#------------------------------------------------------------------------------#
# Execute main menu
	main_menu
#------------------------------------------------------------------------------#
