#!/bin/bash

source config/homepi.conf
source config/poolpi.conf
source src/base_script.sh
source src/faac_install.sh
source src/homebridge_install.sh
source src/homebridge_service_install.sh
source src/nodejs_install.sh
source src/system_update.sh
source src/npm_install.sh
source poolpi/circuit_status.sh
source poolpi/circuit_toggle.sh
source poolpi/circuit_select.sh

# Set Script base directory
	_base_dir() {
		_install_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	}

# Pool Menu
	pool_menu()  {
		## Header
			HEADING="HomeBridge"
		## Write out the menu options array
			### Use Double Quotes for Text
				l0=(
					"Circuit Status"
					"Circuit Toogle"
					"Return"
				)
		## Map Menu to command Array
			### Use Single Quotes for Commands
				opt0=(
					'circuit_status_fn'
					'circuit_toggle_fn'
					'main_menu'
					)
		## Execute Menu Function
			g_menu_fn
	}



# Main Menu
	main_menu()  {
		## Header
			HEADING="HomeBridge"
		## Write out the menu options array
			### Use Double Quotes for Text
				l0=(
					"Update Raspbian-Lite"
					"Install Dependencies"
					"NodeJS install"
					"Install Homebridge"
					"Install systemd Homebridge service files"
					"Install HomeBridge config.json"
					"Start HomeBridge services"
					"Show HomeBridge Service Status"
					"FAAC GPIO Door Opener"
					"Pool PI Menu"
					"Exit"
				)
		## Map Menu to command Array
			### Use Single Quotes for Commands
				opt0=(
					'_base_update'
					'_depends_install'
					'_node_install'
					'_install_homebridge_main'
					'_homebridge_defaults_setup'
					'_config_json_setup'
					'_start_homebridge_fn'
					'_service_status'
					'_faac_install'
					'pool_menu'
					'exit'
					)
		## Execute Menu Function
			g_menu_fn
	}
# Set Script _base_dir
	_base_dir
# Execute set color function
 _set_colors
# Execute super user test
 _su_test
# Execute main menu
	main_menu
