source config/base.conf
source config/example.conf
source config/homebridge.conf
source config/npm.conf
source config/poolcontroller.conf
source config/service_list.conf
source config/systemd.conf
source HomeBridge/homebridge_install.sh
source HomeBridge/homebridge_service_install.sh
source npm/npm_status.sh
source poolController/poolcontroller_install.sh
source poolController/poolcontroller_service_install.sh
source src/base_script.sh
source src/faac_install.sh
source src/_nodejs_install.sh
source src/npm_git_install.sh
source src/npm_install.sh
source src/_system_update.sh
source src/systemd_service_setup.sh
source src/systemd_services.sh
source src/user_create.sh
