source FAAC/faac.conf
source system/base_dependency.conf
source system/global.conf
source HomeBridge/homebridge.conf
source PoolController/PoolController.conf
source NodeJS/npm.conf
source cmdswitch2/cmdswitch2.conf
source systemd/service_list.conf
source systemd/systemd.conf
source FAAC/faac_install.sh
source system/homepi_installer.sh
source system/homepi_user_create.sh
source system/system_update.sh
source system/base_script.sh
source system/system_users_groups.sh
source HomeBridge/homebridge_json_setup.sh
source HomeBridge/homebridge_install.sh
source HomeBridge/systemd_homebridge.sh
source menu.sh
source PoolController/poolcontroller_service_install.sh
source PoolController/poolcontroller_install.sh
source NodeJS/nodejs_install.sh
source NodeJS/npm_scripts.sh
source NodeJS/npm_git_install.sh
source cmdswitch2/cmdswitch2_cmd_install.sh
source systemd/systemd_services.sh
source systemd/systemd_service_setup.sh
